Feature/profile
danill1278/ita-tools pull request #22
Opened 2020-01-17 20:23 UTC by letrylesha

![image](https://user-images.githubusercontent.com/56232429/72643646-3bcb5580-3980-11ea-9edc-662d87e9e42a.png)
![image](https://user-images.githubusercontent.com/56232429/72643661-40900980-3980-11ea-8f20-18d8613248bd.png)

2020-01-17 20:35 UTC, Drews99 commented on src/components/App/ContentWrapper/HomePage/Tiles/Tiles.tsx
> +          tiles.map((tile: TileInterface) => <TileItem tile={tile} key={tile.id} />)
gj

2020-01-17 20:39 UTC, drews-believer approved these changes
not bad)

2020-01-17 20:50 UTC, letrylesha commented on src/components/App/ContentWrapper/HomePage/Tiles/Tiles.tsx
> +          tiles.map((tile: TileInterface) => <TileItem tile={tile} key={tile.id} />)
Thanks bro

2020-01-18 10:54 UTC, CBond05 approved these changes

2020-01-20 10:59 UTC, didevgen requested changes

2020-01-20 10:59 UTC, didevgen commented on package.json
> +    "chartjs": "^0.3.24",
?)

2020-01-20 10:59 UTC, didevgen commented on src/components/App/App.css
> +}
h3, h4

2020-01-20 10:59 UTC, didevgen commented on src/components/App/ContentWrapper/Chart/Chart.tsx
> +    <div style={{ position: "relative", height: "350px", width: "90%", margin: '0 auto' }}>
use styled component

2020-01-20 10:59 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +        src="https://media-exp2.licdn.com/dms/image/C4D03AQHrET7kILmAXg/profile-displayphoto-shrink_200_200/0?e=1584576000&v=beta&t=6YQmC2IJ9grgB9FICDQvvlCYvRgyzErzsGH2jph3fKM"
move to the constant

2020-01-20 10:59 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfileInfo/ProfileInfo.tsx
> +        2. Group:
use spans around text elements

2020-01-20 10:59 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfilePage.tsx
> +  }, []);
just useEffect

2020-01-20 10:59 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfilePage.tsx
> +    return <div>Loading</div>
maybe spinner is better?

2020-01-20 10:59 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfilePage.tsx
> +        </div>
don't see the reason to wrap with div

2020-01-20 10:59 UTC, didevgen commented on src/store/profile/ProfileReducer.ts
> +export default profileReducer;
don't see reflection in unit tests (applicable to all another sagas)

2020-01-20 11:16 UTC, letrylesha commented on package.json
> +    "chartjs": "^0.3.24",
it is new feature))0

2020-01-21 15:33 UTC, letrylesha commented on src/components/App/ContentWrapper/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +        src="https://media-exp2.licdn.com/dms/image/C4D03AQHrET7kILmAXg/profile-displayphoto-shrink_200_200/0?e=1584576000&v=beta&t=6YQmC2IJ9grgB9FICDQvvlCYvRgyzErzsGH2jph3fKM"
its temporarily path

2020-01-21 15:46 UTC, closed without merging