Get and edit avatar in profile
danill1278/ita-tools pull request #33
Opened 2020-01-21 23:05 UTC by letrylesha

![image](https://user-images.githubusercontent.com/56232429/72850972-6ccac380-3cbb-11ea-89a2-1091aec17a84.png)
![image](https://user-images.githubusercontent.com/56232429/72851012-89ff9200-3cbb-11ea-80b1-fbe4d5fff405.png)
![image](https://user-images.githubusercontent.com/56232429/72851023-91bf3680-3cbb-11ea-9d9e-58779b9371b3.png)

2020-01-22 10:13 UTC, didevgen requested changes

2020-01-22 10:13 UTC, didevgen commented on src/components/App/ContentWrapper/ContentWrapper.tsx
> +  console.log(!!props.id);
really?

2020-01-22 10:13 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +        src={url || ''}
better to use default image instead of ''

2020-01-22 10:13 UTC, didevgen commented on src/components/App/ContentWrapper/ProfilePage/ProfileInfo/ProfileInfo.tsx
> +      putFile(avatar, getFileTypes.avatar.path, getFileTypes.avatar.name, uid);
separate avatar updating from update data

2020-01-22 10:13 UTC, didevgen commented on src/sagas/profile/profile.sagas.ts
> +    const userAvatarUrl = yield getFile(getFileTypes.avatar.path, getFileTypes.avatar.name, Cookies.get("uid") || '');
use constant with correct typo

2020-01-22 11:03 UTC, danill1278 approved these changes

2020-01-23 14:14 UTC, yanosh-almashi approved these changes

2020-01-23 15:25 UTC, drews-believer approved these changes

2020-01-23 15:25 UTC, iAmDrews commented on src/components/App/ContentWrapper/ContentWrapper.tsx
> +  console.log(!!props.id);
Will be interface for props?)

2020-01-23 15:26 UTC, CBond05 approved these changes

2020-01-23 16:04 UTC, letrylesha commented on src/components/App/ContentWrapper/ContentWrapper.tsx
> +  console.log(!!props.id);
It's tmp, i'll remove

2020-01-23 17:16 UTC, didevgen approved these changes

2020-01-23 17:16 UTC, didevgen commented on src/api/profile/ProfileApi.ts
> +      }
why switch? 
YAGNI principle

2020-01-23 17:16 UTC, didevgen commented on src/components/App/Auth/Signup/Signup.tsx
> +  const [avatar, setAvatar] = useState(null);
just useState

2020-01-23 17:16 UTC, didevgen commented on src/api/profile/ProfileApi.ts
>  export const putFile = (file: any, path: string, name: string, uid: string) => {
file has File type

2020-01-23 19:49 UTC, merged